### ISSUE TITLE
Conditional check of boolean value is not consistent

### ISSUE THREAD

**Issue by splashx** [operable/greenbar#56]
# Context

## 1 - doesn't work (unexpected)

JSON: as it should be, with booleans unquoted
Template: explicitly using `== true`

```
$ cat samples/users_reset.json
{
  "results": {
    "username": "john.doe",
    "found": true,
    "reset": false,
    "status_code": 403
  }
}
$ cat samples/users_reset.greenbar
Value of $results.found: ~$results.found~
~if cond=$results.found == true~
moooo
~end~
$ docker run --rm -v $PWD:/samples -w /samples gbexec:dev -s users_reset.greenbar users_reset.json
Value of $results.found: true
$
```

## 2 - works (expected)

JSON: as it should be, with booleans unquoted (unmodified from # 1)
Template: *implicitly* using `== true`

```
$ cat samples/users_reset.json
{
  "results": {
    "username": "john.doe",
    "found": true,
    "reset": false,
    "status_code": 403
  }
}
$ cat samples/users_reset.greenbar
Value of $results.found: ~$results.found~
~if cond=$results.found~
moooo
~end~
$ docker run --rm -v $PWD:/samples -w /samples gbexec:dev -s users_reset.greenbar users_reset.json
Value of $results.found: true
moooo
$
```

## 3 - works (unexpected)

JSON: note quoted `"true"` in `found` (this is bad but was used for debugging)
Template: note unquoted `true` in `cond`

```
$ cat samples/users_reset.json
{
  "results": {
    "username": "john.doe",
    "found": "true",
    "reset": false,
    "status_code": 403
  }
}
$ cat samples/users_reset.greenbar
Value of $results.found: ~$results.found~
~if cond=$results.found == true~
moooo
~end~
$ docker run --rm -v $PWD:/samples -w /samples gbexec:dev -s users_reset.greenbar users_reset.json
Value of $results.found: true
moooo
$
```

Source: https://cogbot.slack.com/files/U63JL2XK6/F7TM8H58V/greenbar_templating.txt

**Comment by davejlong** [comment]
Copying from Slack:

> davejlong [6:35 PM]  I have a feeling this is the issue: https://github.com/operable/greenbar/blob/master/src/gb_expr_lexer.xrl#L105
> 
> [6:35] I’ll bet that adding 2 more functions would fix it:
> 
> ```
> boolean(true) ->
>   true;
> boolean(false) ->
>   false.
> ```
>
> [6:36] I’ve just never worked with Erlang’s yecc library before, so I’ll have to play with it.

**Comment by splashx** [comment]
The issue was seen while using https://github.com/operable/gbexec - when the version of greenbar was bumped to `e2c47408b605dd8c9b3b5ef00fb4c6512e2c6ece` @ gbexec the issue went away. Closing.
